### ISSUE TITLE
CORS issue 

### ISSUE THREAD

**Issue by idream3** [christianalfoni/cerebral-boilerplate#1]
Hey @christianalfoni,

Getting s cross domain issue with fresh install of this boilerplate:

```
XMLHttpRequest cannot load http://localhost:8080/socket.io/?
EIO=3&transport=polling&t=1432603927528-0.
No 'Access-Control-Allow-Origin' header is present on the requested resource.
Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 404.
```

Sorry I don't know enough about node server to know what is going on. I tried googling to add CORS support, but nothing I tried worked :)

**Comment by christianalfoni** [comment]
Hi @idream3 ,

Hm, are you running something else on port 8080?

Maybe I should change it to 3001. Often something already runs on 8080.

**Comment by christianalfoni** [comment]
Changed it now, try again :-)

**Comment by idream3** [comment]
Ahh very good! she's up and running thanks :)
